# Generated by Django 4.1.3 on 2022-12-14 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='photo',
            field=models.ImageField(default=1, upload_to='admins'),
            preserve_default=False,
        ),
    ]
