# Generated by Django 4.1.3 on 2022-12-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('M.PHIL', 'M.Phil'), ('PH.D', 'PhD')], default='BACHELOR', max_length=10)),
                ('session_name', models.CharField(choices=[('ARTS', 'Arts'), ('SCIENCE', 'Science'), ('Commerce', 'Commerce'), ('BUSINESS', 'Business')], default='ARTS', max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
    ]
