# Generated by Django 4.1.3 on 2022-12-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='session_name',
            field=models.CharField(blank=True, choices=[('ARTS', 'Arts'), ('SCIENCE', 'Science'), ('Commerce', 'Commerce'), ('BUSINESS', 'Business')], max_length=10, null=True),
        ),
    ]
