# Generated by Django 4.1.3 on 2022-12-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_courses_session_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
            ],
            options={
                'verbose_name': 'Rank Holder',
                'verbose_name_plural': 'Rank Holders',
            },
        ),
    ]
