# Generated by Django 4.1.3 on 2022-12-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_rankholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankholder',
            name='photo',
            field=models.ImageField(default='ok', upload_to='rank_holders'),
            preserve_default=False,
        ),
    ]
