# Generated by Django 4.1.3 on 2022-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_rankholder_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='univ_player/')),
            ],
            options={
                'verbose_name': 'University Player',
                'verbose_name_plural': 'University Players',
            },
        ),
    ]
