# Generated by Django 4.1.3 on 2022-12-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeAdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('photo', models.FileField(upload_to='admission/photo')),
                ('signature', models.FileField(upload_to='admission/signature')),
                ('sslc', models.FileField(upload_to='admission/sslc')),
                ('hsc', models.FileField(upload_to='admission/hsc')),
                ('aadhaar', models.FileField(upload_to='admission/aadhaar')),
                ('community', models.FileField(upload_to='admission/community')),
                ('transfer', models.FileField(upload_to='admission/transfer')),
                ('conduct', models.FileField(upload_to='admission/conduct')),
                ('verify', models.BooleanField()),
            ],
            options={
                'verbose_name': 'College Admission Form',
                'verbose_name_plural': 'College Admission Forms',
            },
        ),
    ]
