# Generated by Django 4.1.3 on 2022-12-22 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PgAdmissionFormModel',
            fields=[
                ('collegeadmissionform_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admission.collegeadmissionform')),
                ('degree_certificate', models.FileField(upload_to='admission/degree')),
                ('provisional_certificate', models.FileField(upload_to='admission/provisional')),
            ],
            bases=('admission.collegeadmissionform',),
        ),
    ]
