# Generated by Django 4.1.3 on 2022-12-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'facility', 'verbose_name_plural': 'facilities'},
        ),
    ]
