# Generated by Django 4.1.3 on 2022-12-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_facility_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitytype',
            options={'verbose_name': 'facility type', 'verbose_name_plural': 'facility types'},
        ),
    ]
